# Generated by Django 3.0.2 on 2020-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200113_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
